In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/mutant-ape-collection_PREPROCESSED.csv', index_col=0)

## Initial Analysis

In [7]:
include=["int64", "object"]
df.describe(include=include)

,id,token_id,asset_contract_address,permalink,traits,image_original_url,created_date,current_price,last_sale_total_price,last_sale_event_timestamp,...,value_hat,display_type_hat,max_value_hat,trait_count_hat,order_hat,value_mouth,display_type_mouth,max_value_mouth,trait_count_mouth,order_mouth
count,1.184300e+04,11843.000000,11843,11843,11843,11843,11843,11843,11843,11843,...,11843,2645,2645,11843,2645,11843,5,5,11843,5
unique,NaN,NaN,1,11843,11843,11843,1,530,1498,7912,...,73,1,1,65,1,67,1,1,60,1
top,NaN,NaN,0x60e4d786628fea6478f785a6d7e704777c86a7c6,https://opensea.io/assets/0x60e4d786628fea6478...,"[{'trait_type': 'Mouth', 'value': 'M1 Bored Un...",https://ipfs.io/ipfs/QmURua8bNrAwX76Tp6G9t6Los...,2021-08-29T00:41:59.548458,Not on sale. Taking offers.,Not available.,Not available.,...,-,-,-,-,-,M1 Bored,-,-,3032,-
freq,NaN,NaN,11843,1,1,1,11843,9800,3362,3362,...,2645,2645,2645,2645,2645,2039,5,5,2039,5
mean,4.605787e+07,6133.845394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.948876e+07,3781.787504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,4.218842e+07,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,4.219661e+07,2960.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,4.220168e+07,5921.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,4.220609e+07,8881.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.906658e+08,14648.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df['current_price'].value_counts()[0:10]

Not on sale. Taking offers.    9800
25.0                            118
20.0                             96
30.0                             94
50.0                             58
35.0                             55
40.0                             45
100.0                            39
21.0                             31
22.0                             30
Name: current_price, dtype: int64

### Findings
- All assets are minted under the same contract address
- All assets have unique traits (obviously)
- All assets were created on the same data 29.08.2021
- 9800 assets don't have a sales price (as of data collection date - 08.01.2022)

In [24]:
df.iloc[4]

id                                                                    42189032
token_id                                                                     4
asset_contract_address              0x60e4d786628fea6478f785a6d7e704777c86a7c6
permalink                    https://opensea.io/assets/0x60e4d786628fea6478...
traits                       [{'trait_type': 'Background', 'value': 'M1 Yel...
image_original_url           https://ipfs.io/ipfs/QmWRGQUs6yRUinC8d3woj6dgZ...
created_date                                        2021-08-29T00:41:59.548458
current_price                                      Not on sale. Taking offers.
last_sale_total_price                                           Not available.
last_sale_event_timestamp                                       Not available.
value_background                                                     M1 Yellow
display_type_background                                                    NaN
max_value_background                                                       NaN
trait_count_background                                                    1775
order_background                                                           NaN
value_clothes                                                    M1 Blue Dress
display_type_clothes                                                       NaN
max_value_clothes                                                          NaN
trait_count_clothes                                                        125
order_clothes                                                              NaN
value_earring                                                   M1 Silver Stud
display_type_earring                                                       NaN
max_value_earring                                                          NaN
trait_count_earring                                                       1082
order_earring                                                              NaN
value_eyes                                                            M1 Bored
display_type_eyes                                                          NaN
max_value_eyes                                                             NaN
trait_count_eyes                                                          2302
order_eyes                                                                 NaN
value_fur                                                         M1 Death Bot
display_type_fur                                                           NaN
max_value_fur                                                              NaN
trait_count_fur                                                            269
order_fur                                                                  NaN
value_hat                                                           M1 S&m Hat
display_type_hat                                                           NaN
max_value_hat                                                              NaN
trait_count_hat                                                            307
order_hat                                                                  NaN
value_mouth                                                          M1 Jovial
display_type_mouth                                                         NaN
max_value_mouth                                                            NaN
trait_count_mouth                                                          386
order_mouth                                                                NaN
Name: 4, dtype: object

In [23]:
df.iloc[4]['current_price']

'Not on sale. Taking offers.'